name: doconfly
on:
  push:
    branches:
      - master
    tags:
      - v*
 
jobs:
  doconfly:
    name: doconfly job
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY" }}
      TAKOYAKI: ${{ secrets.TAKOYAKI }}
      USER: ${{ secrets.USER }}
    steps:
      - run: 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
      - run: eval $(ssh-agent -s)
      - run: echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - run: mkdir -p ~/.ssh
      - run: chmod 700 ~/.ssh
      - run: ssh-keyscan -p $PORT $TAKOYAKI >> ~/.ssh/known_hosts
      - run: chmod 644 ~/.ssh/known_hosts
      - run: ssh $USER@$TAKOYAKI -p $PORT "less toto"
