name: doconfly
on:
  push:
    branches:
      - master
    tags:
      - v*
 
jobs:
  doconfly:
    name: doconfly job
    runs-on: ubuntu-latest
      steps:
        - run:
            - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'       
